apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: shsingh-tap 
  janus-idp.io/tekton: shsingh-tap
  backstage.io/kubernetes-id: shsingh-tap
  backstage.io/kubernetes-namespace: shsingh-tap 
  app.kubernetes.io/part-of: shsingh-tap
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml