apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: shsingh-tap
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: tssc-quay-quay-tssc-quay.apps.shailendra14k.in/tssc/tap:9bf214ccd2d510e99deac5ed35987e2bf4aaf9e1@sha256:925222b41aeaddcb29473f82c231710b7710cbf916517c44973cbd31c3b1009f
          name: container-image
