apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: shsingh-tap
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: tssc-quay-quay-tssc-quay.apps.shailendra14k.in/tssc/tap:e633b1168863e01150c6b20dd17333b8f58f02da@sha256:32e0df2f60d5b5ab3cd44db04c32b88f77dac1bdf1d218a0d264f35569f1fd78
          name: container-image
