apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: shsingh-tap
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: tssc-quay-quay-tssc-quay.apps.shailendra14k.in/tssc/tap:495567217a4ccc8e0a9511879e415754486e1602@sha256:47e1103009543a5bbda4343775822087cd7b2027d713a6aa80f0b3fdf9694f17
          name: container-image
